### ISSUE TITLE
iOS example first run crash

### ISSUE THREAD

**Issue by MikePodgorniy** [iyegoroff/make-react-native-package#3]
Hello, how to fix this?

xcode 11.3.1

1. `npx make-react-native-package -p react-native-add-to-wallet -g MikePodgorniy -m "AddToWallet"`
2. open ReactNativeAddToWalletExample.xcworkspace
3. run

![Снимок экрана 2020-02-05 в 10 32 53](https://user-images.githubusercontent.com/5052136/73825083-05a52700-4804-11ea-89f4-5a6cd5bac3f8.png)

Exception 'Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.' was thrown while invoking show on target RNATWAddToWallet with params (
    AddToWallet
)
callstack: (
	0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
	2   Foundation                          0x00007fff258d7b64 -[NSISEngine tryToOptimizeReturningMutuallyExclusiveConstraints] + 0
	3   Foundation                          0x00007fff258d8228 -[NSISEngine withBehaviors:performModifications:] + 25
	4   UIKitCore                           0x00007fff4849068a -[UIView(UIConstraintBasedLayout) _calculatedSystemLayoutSizeFittingSize:withHorizontalFittingPriority:verticalFittingPriority:hasIntentionallyCollapsedHeight:] + 1198
	5   UIKitCore                           0x00007fff48491b1b -[UIView(AdditionalLayoutSupport) _systemLayoutSizeFittingSize:withHorizontalFittingPriority:verticalFittingPriority:hasIntentionallyCollapsedHeight:] + 694
	6   UIKitCore                           0x00007fff47650745 -[_UIAlertControllerView _minimumSizeForAllActions] + 593
	7   UIKitCore                           0x00007fff4764bd23 -[_UIAlertControllerView _itemSizeForHorizontalLayout:visualStyleRequiresActionRepresentationToFitItemSize:] + 36
	8   UIKitCore                           0x00007fff4764c2b0 -[_UIAlertControllerView _actionLayoutDirectionChanged] + 109
	9   UIKitCore                           0x00007fff47650f07 -[_UIAlertControllerView _updateStyleForIdiomChange:] + 224
	10  UIKitCore                           0x00007fff47650d8a -[_UIAlertControllerView _setVisualStyle:] + 282
	11  UIKitCore                           0x00007fff47631df9 -[UIAlertController loadView] + 397
	12  UIKitCore                           0x00007fff47a13aca -[UIViewController loadViewIfRequired] + 172
	13  UIKitCore                           0x00007fff47a14277 -[UIViewController view] + 27
	14  UIKitCore                           0x00007fff47a2b52e -[UIViewController _setPresentationController:] + 100
	15  UIKitCore                           0x00007fff47a23d25 -[UIViewController _presentViewController:modalSourceViewController:presentationController:animationController:interactionController:completion:] + 1318
	16  UIKitCore                           0x00007fff47a25798 -[UIViewController _presentViewController:withAnimationController:completion:] + 4349
	17  UIKitCore                           0x00007fff47a2801b __63-[UIViewController _presentViewController:animated:completion:]_block_invoke + 98
	18  UIKitCore                           0x00007fff47a28533 -[UIViewController _performCoordinatedPresentOrDismiss:animated:] + 511
	19  UIKitCore                           0x00007fff47a27f79 -[UIViewController _presentViewController:animated:completion:] + 187
	20  UIKitCore                           0x00007fff47a281e0 -[UIViewController presentViewController:animated:completion:] + 150
	21  ReactNativeAddToWalletExample       0x000000010505c6fa $s26react_native_add_to_wallet11AddToWalletC4showyySSF + 426
	22  ReactNativeAddToWalletExample       0x000000010505cb83 $s26react_native_add_to_wallet11AddToWalletC4showyySSFTo + 83
	23  CoreFoundation                      0x00007fff23c7820c __invoking___ + 140
	24  CoreFoundation                      0x00007fff23c753af -[NSInvocation invoke] + 319
	25  CoreFoundation                      0x00007fff23c75684 -[NSInvocation invokeWithTarget:] + 68
	26  ReactNativeAddToWalletExample       0x0000000104e92b62 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2658
	27  ReactNativeAddToWalletExample       0x0000000104e96c97 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 791
	28  ReactNativeAddToWalletExample       0x0000000104e967a3 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 131
	29  ReactNativeAddToWalletExample       0x0000000104e96719 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 25
	30  libdispatch.dylib                   0x000000010655ddd4 _dispatch_call_block_and_release + 12
	31  libdispatch.dylib                   0x000000010655ed48 _dispatch_client_callout + 8
	32  libdispatch.dylib                   0x00000001065655ef _dispatch_lane_serial_drain + 788
	33  libdispatch.dylib                   0x000000010656617f _dispatch_lane_invoke + 422
	34  libdispatch.dylib                   0x0000000106571a4e _dispatch_workloop_worker_thread + 719
	35  libsystem_pthread.dylib             0x00007fff524636fc _pthread_wqthread + 290
	36  libsystem_pthread.dylib             0x00007fff52462827 start_wqthread + 15
)

RCTFatal
facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&)
facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const
invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_lane_serial_drain
_dispatch_lane_invoke
_dispatch_workloop_worker_thread
_pthread_wqthread
start_wqthread

**Comment by iyegoroff** [comment]
Hello, @MikePodgorniy 
Can you check if this bug is being reproduced on iOS 12 ?

**Comment by MikePodgorniy** [comment]
ok, I will check it on 12.4

**Comment by iyegoroff** [comment]
Just a guess - maybe removal of [this method](https://github.com/iyegoroff/make-react-native-package/blob/master/template/ios/component-template/%7B%7BobjcPrefix%7D%7D%7B%7BlazyPascalCaseComponentName%7D%7DManager.m#L10-L13) could fix this.

**Comment by MikePodgorniy** [comment]
My current: **RNATWAddToWallet.m**  

```
#import <React/RCTBridgeModule.h>

@interface RCT_EXTERN_MODULE(RNATWAddToWallet, NSObject)

+ (BOOL)requiresMainQueueSetup
{
  return YES;
}

RCT_EXTERN_METHOD(show:(NSString *)message)

@end
```

I think something wrong in the current template because my file doesn't contain these lines.
Then I added 'methodQueue' method and right now everything is fine.

https://github.com/iyegoroff/make-react-native-package/blob/master/template/ios/module-template/%7B%7BobjcPrefix%7D%7D%7B%7BlazyPascalCaseModuleName%7D%7D.m

![Снимок экрана 2020-02-05 в 14 24 30](https://user-images.githubusercontent.com/5052136/73841512-81fb3280-4823-11ea-869a-1e7ad449786f.png)

**Comment by iyegoroff** [comment]
Ok, I didn't notice that you have a 'module' template. I'll review and update these templates later, thanks for your feedback.

**Comment by MikePodgorniy** [comment]
`-m "AddToWallet"`  😄
